all:
	g++ -std=c++11 -c employee.cpp administrativepersonnel.cpp academicpersonnel.cpp researchassistant.cpp officer.cpp lecturer.cpp university.cpp secretary.cpp  main.cpp 
	g++ employee.o administrativepersonnel.o academicpersonnel.o researchassistant.o officer.o lecturer.o secretary.o university.o main.o -o hw5

run:
	./hw5

clean:
	rm *.o hw5
	clear