all:
	g++ -std=c++11 -c employee.cpp administrativepersonnel.cpp academicpersonnel.cpp researchassistant.cpp officer.cpp lecturer.cpp university.cpp secretary.cpp complex.cpp main.cpp 
	g++ employee.o administrativepersonnel.o academicpersonnel.o researchassistant.o officer.o lecturer.o secretary.o university.o complex.o main.o -o hw6

run:
	./hw6

clean:
	rm *.o hw6
	clear