all:
	g++ -std=c++11 -c employee.cpp capitalisteducation.cpp administrativepersonnel.cpp academicpersonnel.cpp liberaleducation.cpp researchassistant.cpp officer.cpp  strcutemp.cpp lecturer.cpp university.cpp secretary.cpp complex.cpp communisteducation.cpp main.cpp 
	g++ employee.o administrativepersonnel.o academicpersonnel.o capitalisteducation.o liberaleducation.cpp researchassistant.o officer.o lecturer.o strcutemp.o secretary.o university.o complex.o communisteducation.o main.o -o hw7

run:
	./hw7

clean:
	rm *.o hw7
	clear
